#!/usr/bin/env python3

# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later

import json
import sys
import agent
import secrets
import base64
from agent.ldapproxy import Ldapproxy

# Try to parse the stdin as JSON.
data = json.load(sys.stdin)

# MariaDB config
MARIADB_ROOT_PASSWORD = data.get("MARIADB_ROOT_PASSWORD", "Nethesis@1234")
MARIADB_DATABASE = data.get("MARIADB_DATABASE", "semaphore")
MARIADB_USER = data.get("MARIADB_USER", "semaphore")
MARIADB_PASSWORD = data.get("MARIADB_PASSWORD", "Nethesis@1234")
MARIADB_AUTO_UPGRADE = data.get("MARIADB_AUTO_UPGRADE", "1")

maria_db = {
    "MARIADB_ROOT_PASSWORD": MARIADB_ROOT_PASSWORD,
    "MARIADB_DATABASE": MARIADB_DATABASE,
    "MARIADB_USER": MARIADB_USER,
    "MARIADB_PASSWORD": MARIADB_PASSWORD,
    "MARIADB_AUTO_UPGRADE": MARIADB_AUTO_UPGRADE
}
agent.write_envfile("database.env", maria_db)

# Semaphore app config
SECRET_KEY_BYTES = secrets.token_bytes(32)
SECRET_KEY = base64.b64encode(SECRET_KEY_BYTES).decode('utf-8')

SEMAPHORE_ADMIN_PASSWORD = data.get("SEMAPHORE_ADMIN_PASSWORD", "password")
SEMAPHORE_ADMIN_NAME = data.get("SEMAPHORE_ADMIN_NAME", "admin")
SEMAPHORE_ADMIN_EMAIL = data.get("SEMAPHORE_ADMIN_EMAIL", "admin@admin.com")
SEMAPHORE_ADMIN = data.get("SEMAPHORE_ADMIN", "admin")

# Get SMTP from SmartHost
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

MAIL_DRIVER = "smtp"
MAIL_FROM_ADDRESS = smtp_settings['username']
MAIL_FROM_NAME = f"DOCMOST <{MAIL_FROM_ADDRESS}>"
SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']

# Optional Gotify + Telegram
SEMAPHORE_GOTIFY_ALERT = data.get("SEMAPHORE_GOTIFY_ALERT", "False")
SEMAPHORE_GOTIFY_URL = data.get("SEMAPHORE_GOTIFY_URL", "")
SEMAPHORE_GOTIFY_TOKEN = data.get("SEMAPHORE_GOTIFY_TOKEN", "")

SEMAPHORE_TELEGRAM_ALERT = data.get("SEMAPHORE_TELEGRAM_ALERT", "False")
SEMAPHORE_TELEGRAM_CHAT = data.get("SEMAPHORE_TELEGRAM_CHAT", "")
SEMAPHORE_TELEGRAM_TOKEN = data.get("SEMAPHORE_TELEGRAM_TOKEN", "")

# LDAP Configuration
ldap_domain = data.get("ldap_domain", "")
agent.set_env("LDAP_DOMAIN", ldap_domain)

# Clear old LDAP values
for key in [
    "LDAP_HOSTNAME", "LDAP_PORT", "LDAP_SEARCH_BIND_DN", "LDAP_SEARCH_BIND_PASSWORD",
    "LDAP_USER_BASE_DN", "LDAP_MEMBER_ATTRIBUTE", "LDAP_MEMBER_ATTRIBUTE_TYPE",
    "LDAP_GROUP_BASE_DN", "LDAP_USERNAME_ATTRIBUTE", "LDAP_USER_SEARCH_FILTER",
    "LDAP_GROUP_SEARCH_FILTER"]:
    agent.unset_env(key)

SEMAPHORE_LDAP_ENABLE = "False"
SEMAPHORE_LDAP_BIND_DN = ""
SEMAPHORE_LDAP_BIND_PASSWORD = ""
SEMAPHORE_LDAP_SERVER = ""
SEMAPHORE_LDAP_SEARCH_DN = ""
SEMAPHORE_LDAP_SEARCH_FILTER = ""
SEMAPHORE_LDAP_NEEDTLS = "False"
SEMAPHORE_LDAP_MAPPING_DN = "dn"
SEMAPHORE_LDAP_MAPPING_MAIL = "mail"
SEMAPHORE_LDAP_MAPPING_UID = "uid"
SEMAPHORE_LDAP_MAPPING_CN = "cn"

if ldap_domain:
    agent.bind_user_domains([ldap_domain])
    odom = Ldapproxy().get_domain(ldap_domain)
    base_dn = odom['base_dn']

    agent.set_env("LDAP_HOSTNAME", "10.0.2.2")
    agent.set_env("LDAP_PORT", odom['port'])
    agent.set_env("LDAP_SEARCH_BIND_DN", odom['bind_dn'])
    agent.set_env("LDAP_SEARCH_BIND_PASSWORD", odom['bind_password'])

    SEMAPHORE_LDAP_ENABLE = "True"
    SEMAPHORE_LDAP_BIND_DN = odom['bind_dn']
    SEMAPHORE_LDAP_BIND_PASSWORD = odom['bind_password']
    SEMAPHORE_LDAP_SERVER = "10.0.2.2"
    SEMAPHORE_LDAP_NEEDTLS = "False"

    if odom['schema'] == "rfc2307":
        SEMAPHORE_LDAP_SEARCH_DN = f"ou=People,{base_dn}"
    elif odom['schema'] == "ad":
        SEMAPHORE_LDAP_SEARCH_DN = f"cn=Users,{base_dn}"
        SEMAPHORE_LDAP_SEARCH_FILTER = "(&(objectClass=top)(objectClass=user)(objectClass=person)(objectClass=organizationalPerson))"

else:
    agent.bind_user_domains([])

app_config = {
    "SEMAPHORE_DB_USER": MARIADB_USER,
    "SEMAPHORE_DB_PASS": MARIADB_PASSWORD,
    "SEMAPHORE_DB_HOST": "mariadb-app",
    "SEMAPHORE_DB_PORT": "3306",
    "SEMAPHORE_DB_DIALECT": "mysql",
    "SEMAPHORE_DB": MARIADB_DATABASE,
    "SEMAPHORE_ADMIN_PASSWORD": SEMAPHORE_ADMIN_PASSWORD,
    "SEMAPHORE_ADMIN_NAME": SEMAPHORE_ADMIN_NAME,
    "SEMAPHORE_ADMIN_EMAIL": SEMAPHORE_ADMIN_EMAIL,
    "SEMAPHORE_ADMIN": SEMAPHORE_ADMIN,
    "SEMAPHORE_ACCESS_KEY_ENCRYPTION": SECRET_KEY,

    # SMTP
    "SEMAPHORE_EMAIL_SENDER": MAIL_FROM_NAME,
    "SEMAPHORE_EMAIL_HOST": SMTP_HOST,
    "SEMAPHORE_EMAIL_PORT": str(SMTP_PORT),
    "SEMAPHORE_EMAIL_USERNAME": SMTP_USERNAME,
    "SEMAPHORE_EMAIL_PASSWORD": SMTP_PASSWORD,

    # Gotify
    "SEMAPHORE_GOTIFY_ALERT": SEMAPHORE_GOTIFY_ALERT,
    "SEMAPHORE_GOTIFY_URL": SEMAPHORE_GOTIFY_URL,
    "SEMAPHORE_GOTIFY_TOKEN": SEMAPHORE_GOTIFY_TOKEN,

    # Telegram
    "SEMAPHORE_TELEGRAM_ALERT": SEMAPHORE_TELEGRAM_ALERT,
    "SEMAPHORE_TELEGRAM_CHAT": SEMAPHORE_TELEGRAM_CHAT,
    "SEMAPHORE_TELEGRAM_TOKEN": SEMAPHORE_TELEGRAM_TOKEN,

    # LDAP
    "SEMAPHORE_LDAP_ENABLE": SEMAPHORE_LDAP_ENABLE,
    "SEMAPHORE_LDAP_BIND_DN": SEMAPHORE_LDAP_BIND_DN,
    "SEMAPHORE_LDAP_BIND_PASSWORD": SEMAPHORE_LDAP_BIND_PASSWORD,
    "SEMAPHORE_LDAP_SERVER": SEMAPHORE_LDAP_SERVER,
    "SEMAPHORE_LDAP_SEARCH_DN": SEMAPHORE_LDAP_SEARCH_DN,
    "SEMAPHORE_LDAP_SEARCH_FILTER": SEMAPHORE_LDAP_SEARCH_FILTER,
    "SEMAPHORE_LDAP_NEEDTLS": SEMAPHORE_LDAP_NEEDTLS,
    "SEMAPHORE_LDAP_MAPPING_DN": SEMAPHORE_LDAP_MAPPING_DN,
    "SEMAPHORE_LDAP_MAPPING_MAIL": SEMAPHORE_LDAP_MAPPING_MAIL,
    "SEMAPHORE_LDAP_MAPPING_UID": SEMAPHORE_LDAP_MAPPING_UID,
    "SEMAPHORE_LDAP_MAPPING_CN": SEMAPHORE_LDAP_MAPPING_CN
}

agent.write_envfile("app.env", app_config)
agent.dump_env()
