#!/usr/bin/env python3
#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Read configuration
#

import os, sys, json, agent
from agent.ldapproxy import Ldapproxy

# LDAP domains for combo-box
lp = Ldapproxy()
domains = [{"name": k, "label": k, "value": k} for k in lp.get_domains_list()]

config = {
    "host":         os.getenv("TRAEFIK_HOST", ""),
    "http2https":   os.getenv("TRAEFIK_HTTP2HTTPS") == "True",
    "lets_encrypt": os.getenv("TRAEFIK_LETS_ENCRYPT") == "True",
    "ldap_domain":  os.getenv("LDAP_DOMAIN", ""),
    "domains_list": domains,

    # Admin credentials – match UI field names exactly
    "SEMAPHORE_ADMIN":          os.getenv("SEMAPHORE_ADMIN", ""),
    "SEMAPHORE_ADMIN_NAME":     os.getenv("SEMAPHORE_ADMIN_NAME", ""),
    "SEMAPHORE_ADMIN_EMAIL":    os.getenv("SEMAPHORE_ADMIN_EMAIL", ""),
    "SEMAPHORE_ADMIN_PASSWORD": os.getenv("SEMAPHORE_ADMIN_PASSWORD", ""),
}

json.dump(config, fp=sys.stdout)